### ISSUE TITLE
How to register alternate events?

### ISSUE THREAD

**Issue by drnic** [hopsoft/turbo_boost-commands#56]
In https://github.com/hopsoft/turbo_reflex/blob/main/README.md#reflex-triggers it suggests we can override default events with `TurboReflex.registerEvent` but this method doesn't exist for me. 

I found `TurboReflex.registerEventDelegate` but I couldn't get it to register `onmouseover` or some other event types.

```js
TurboReflex.registerEventDelegate('onmouseover', ['p[data-turbo-reflex]'])
```

Similarly, I tried inline custom events like `data-turbo-reflex="onmouseover->CounterReflex#increment"` but didn't see the reflex action trigger.

**Comment by hopsoft** [comment]
You'll want to remove the `on` prefix in the event name. Here's an example.

```js
TurboReflex.registerEventDelegate('mouseover', ['p[data-turbo-reflex]'])
```
<img width="1017" alt="TurboReflex 2022-12-18 05-50-23" src="https://user-images.githubusercontent.com/32920/208299391-6a57726e-feff-44de-a540-6ea1fd463a94.png">

Let me know if this works for you.

**Comment by hopsoft** [comment]
Note that after the lib rebrand to TurboBoost Commands, this code should be changed to:

```js
TurboBoost.Commands.registerEventDelegate(...)
```

**Comment by adamjleonard** [comment]
@hopsoft I wanted to follow up on this conversation. I've attempted to register a keyup, keydown and keypress event but unfortunately it didn't trigger the command.

I unfortunately don't have a sample project for you at the moment and I'll see if I can take this local and do some debugging myself, but just wanted to put it on your radar.

**Comment by hopsoft** [comment]
Interesting. If it helps, this is where/how the library registers the default event delegates. https://github.com/hopsoft/turbo_boost-commands/blob/main/app/javascript/index.js#L92-L98

And here's where the library identifies a match when the even is triggered. https://github.com/hopsoft/turbo_boost-commands/blob/8217e3925fab7cb0f0ca2198f39ef82732dca85b/app/javascript/delegates.js#L17

**Comment by hopsoft** [comment]
Verified that we definitely have a bug related to registering additional events. The click handler is taking precedence. Will dive into this shortly.

**Comment by adamjleonard** [comment]
I tested this current branch against keyup as well and that seems to still fail. I hope tomorrow to actually sit down and take a look at debugging

**Comment by adamjleonard** [comment]
Excuse my stupidity but is there a specific reason to not use something similar to stimulus where you can bind the action with change->Command->method

**Comment by hopsoft** [comment]
Great question. Yes, there is a reason we opt for event delegation over per-element bound event listeners. Low level tools and libraries _(like this one)_ can't make too many assumptions about the JavaScript ecosystem they're running within. 

One example to illustrate the challenges is related to how StimulusReflex implicitly registers a StimulusJS controller for events that declare a data attribute that haven't already registered a StimulusJS controller with similar behavior. Detecting this is problematic because there's no way for the library to know how the JavaScript assets are organized or how they'll be loaded and parsed for a given application. This scenario is exacerbated with new techniques like [import maps](https://html.spec.whatwg.org/multipage/webappapis.html#import-maps) etc... Any client side Stimulus controller that's implicitly wired up can introduce unintentional and unwanted duplicate behavior _(i.e. trigger RPC calls multiple times from a single client side event)_.

Event delegation eliminates this problem entirely, so it doesn't matter how the JavaScript assets are resolved, loaded, and parsed on the client. The primary caveat of delegation being that it limits us to bubbling events.

- abort
- blur
- change
- click
- contextmenu
- dblclick
- error
- focus
- input
- keydown
- keypress
- keyup
- load
- mousedown
- mousemove
- mouseout
- mouseover
- mouseup
- mousewheel
- resize
- scroll
- select
- submit
- unload

Having said that, event delegation also works with custom events and each registered delegate can include multiple selectors per event. Selectors for each delegate can be as simple or as sophisticated as desired.

---

In your example above, I would expect the following delegate to work.

```js
const existingChangeDelegate = TurboBoost.Commands.eventDelegates.find(e => e.name === 'change')
TurboBoost.Commands.registerEventDelegate('change', [...existingChangeDelegate.selectors, '.my-element[data-turbo-command]'])
```

I could probably make this a bit more intuitive though.

**Comment by hopsoft** [comment]
Just created ticket #75 to help with event delegate overrides.
